package com.example.Sword.ui.theme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF5B631E)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFDFE995)
private val onPrimaryContainerLight = Color(0xFF1A1E00)
private val secondaryLight = Color(0xFF5E6144)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFE3E5C1)
private val onSecondaryContainerLight = Color(0xFF1A1D07)
private val tertiaryLight = Color(0xFF3B665B)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFBEECDD)
private val onTertiaryContainerLight = Color(0xFF002019)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF410002)
private val backgroundLight = Color(0xFFFCFAED)
private val onBackgroundLight = Color(0xFF1B1C14)
private val surfaceLight = Color(0xFFFCFAED)
private val onSurfaceLight = Color(0xFF1B1C14)
private val surfaceVariantLight = Color(0xFFE4E3D2)
private val onSurfaceVariantLight = Color(0xFF47483B)
private val outlineLight = Color(0xFF78786A)
private val outlineVariantLight = Color(0xFFC8C7B7)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF303128)
private val inverseOnSurfaceLight = Color(0xFFF3F1E4)
private val inversePrimaryLight = Color(0xFFC3CD7B)
private val surfaceDimLight = Color(0xFFDCDACE)
private val surfaceBrightLight = Color(0xFFFCFAED)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF6F4E7)
private val surfaceContainerLight = Color(0xFFF0EEE1)
private val surfaceContainerHighLight = Color(0xFFEAE9DC)
private val surfaceContainerHighestLight = Color(0xFFE5E3D6)

private val primaryLightMediumContrast = Color(0xFF3F4702)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF717A32)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF42452B)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF747759)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF1E4A3F)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF517D71)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF8C0009)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFDA342E)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFCFAED)
private val onBackgroundLightMediumContrast = Color(0xFF1B1C14)
private val surfaceLightMediumContrast = Color(0xFFFCFAED)
private val onSurfaceLightMediumContrast = Color(0xFF1B1C14)
private val surfaceVariantLightMediumContrast = Color(0xFFE4E3D2)
private val onSurfaceVariantLightMediumContrast = Color(0xFF434437)
private val outlineLightMediumContrast = Color(0xFF5F6052)
private val outlineVariantLightMediumContrast = Color(0xFF7B7C6D)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF303128)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFF3F1E4)
private val inversePrimaryLightMediumContrast = Color(0xFFC3CD7B)
private val surfaceDimLightMediumContrast = Color(0xFFDCDACE)
private val surfaceBrightLightMediumContrast = Color(0xFFFCFAED)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFF6F4E7)
private val surfaceContainerLightMediumContrast = Color(0xFFF0EEE1)
private val surfaceContainerHighLightMediumContrast = Color(0xFFEAE9DC)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFE5E3D6)

private val primaryLightHighContrast = Color(0xFF202500)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF3F4702)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF21240D)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF42452B)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF002820)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF1E4A3F)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF4E0002)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF8C0009)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFCFAED)
private val onBackgroundLightHighContrast = Color(0xFF1B1C14)
private val surfaceLightHighContrast = Color(0xFFFCFAED)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFE4E3D2)
private val onSurfaceVariantLightHighContrast = Color(0xFF24251A)
private val outlineLightHighContrast = Color(0xFF434437)
private val outlineVariantLightHighContrast = Color(0xFF434437)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF303128)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFE9F39D)
private val surfaceDimLightHighContrast = Color(0xFFDCDACE)
private val surfaceBrightLightHighContrast = Color(0xFFFCFAED)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF6F4E7)
private val surfaceContainerLightHighContrast = Color(0xFFF0EEE1)
private val surfaceContainerHighLightHighContrast = Color(0xFFEAE9DC)
private val surfaceContainerHighestLightHighContrast = Color(0xFFE5E3D6)

private val primaryDark = Color(0xFFC3CD7B)
private val onPrimaryDark = Color(0xFF2E3400)
private val primaryContainerDark = Color(0xFF434B05)
private val onPrimaryContainerDark = Color(0xFFDFE995)
private val secondaryDark = Color(0xFFC7C9A7)
private val onSecondaryDark = Color(0xFF2F321A)
private val secondaryContainerDark = Color(0xFF46492F)
private val onSecondaryContainerDark = Color(0xFFE3E5C1)
private val tertiaryDark = Color(0xFFA2D0C2)
private val onTertiaryDark = Color(0xFF06372D)
private val tertiaryContainerDark = Color(0xFF224E43)
private val onTertiaryContainerDark = Color(0xFFBEECDD)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF13140D)
private val onBackgroundDark = Color(0xFFE5E3D6)
private val surfaceDark = Color(0xFF13140D)
private val onSurfaceDark = Color(0xFFE5E3D6)
private val surfaceVariantDark = Color(0xFF47483B)
private val onSurfaceVariantDark = Color(0xFFC8C7B7)
private val outlineDark = Color(0xFF929283)
private val outlineVariantDark = Color(0xFF47483B)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE5E3D6)
private val inverseOnSurfaceDark = Color(0xFF303128)
private val inversePrimaryDark = Color(0xFF5B631E)
private val surfaceDimDark = Color(0xFF13140D)
private val surfaceBrightDark = Color(0xFF393A31)
private val surfaceContainerLowestDark = Color(0xFF0E0F08)
private val surfaceContainerLowDark = Color(0xFF1B1C14)
private val surfaceContainerDark = Color(0xFF202018)
private val surfaceContainerHighDark = Color(0xFF2A2B22)
private val surfaceContainerHighestDark = Color(0xFF35352D)

private val primaryDarkMediumContrast = Color(0xFFC7D17F)
private val onPrimaryDarkMediumContrast = Color(0xFF151800)
private val primaryContainerDarkMediumContrast = Color(0xFF8D964B)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFCBCDAB)
private val onSecondaryDarkMediumContrast = Color(0xFF151804)
private val secondaryContainerDarkMediumContrast = Color(0xFF909374)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFA6D4C6)
private val onTertiaryDarkMediumContrast = Color(0xFF001B14)
private val tertiaryContainerDarkMediumContrast = Color(0xFF6D9A8C)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFBAB1)
private val onErrorDarkMediumContrast = Color(0xFF370001)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF13140D)
private val onBackgroundDarkMediumContrast = Color(0xFFE5E3D6)
private val surfaceDarkMediumContrast = Color(0xFF13140D)
private val onSurfaceDarkMediumContrast = Color(0xFFFDFBEE)
private val surfaceVariantDarkMediumContrast = Color(0xFF47483B)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFCCCCBB)
private val outlineDarkMediumContrast = Color(0xFFA4A494)
private val outlineVariantDarkMediumContrast = Color(0xFF848475)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFE5E3D6)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2B22)
private val inversePrimaryDarkMediumContrast = Color(0xFF444C06)
private val surfaceDimDarkMediumContrast = Color(0xFF13140D)
private val surfaceBrightDarkMediumContrast = Color(0xFF393A31)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0E0F08)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1C14)
private val surfaceContainerDarkMediumContrast = Color(0xFF202018)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF2A2B22)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF35352D)

private val primaryDarkHighContrast = Color(0xFFFAFFC9)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFC7D17F)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
private val secondaryDarkHighContrast = Color(0xFFFBFDD9)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFCBCDAB)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
private val tertiaryDarkHighContrast = Color(0xFFECFFF7)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFA6D4C6)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
private val errorDarkHighContrast = Color(0xFFFFF9F9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
private val onErrorContainerDarkHighContrast = Color(0xFF000000)
private val backgroundDarkHighContrast = Color(0xFF13140D)
private val onBackgroundDarkHighContrast = Color(0xFFE5E3D6)
private val surfaceDarkHighContrast = Color(0xFF13140D)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF47483B)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFDFCEA)
private val outlineDarkHighContrast = Color(0xFFCCCCBB)
private val outlineVariantDarkHighContrast = Color(0xFFCCCCBB)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFE5E3D6)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF282D00)
private val surfaceDimDarkHighContrast = Color(0xFF13140D)
private val surfaceBrightDarkHighContrast = Color(0xFF393A31)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF0E0F08)
private val surfaceContainerLowDarkHighContrast = Color(0xFF1B1C14)
private val surfaceContainerDarkHighContrast = Color(0xFF202018)
private val surfaceContainerHighDarkHighContrast = Color(0xFF2A2B22)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF35352D)


val trustLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val trustDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

val trustMediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

val trustHighContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

val trustMediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

val trustHighContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)



